[package]
name = "cities"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.18.0"
pprof = "0.13.0"
rand = "0.8.5"
raylib = "5.0.1"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }


